GET http://127.0.0.1:8000/collections?page=0&size=10

###

POST http://127.0.0.1:8000/collections
Content-Type: application/json

{
    "label": "MY_LAYER_TEST",
    "properties": {
        "Layer": "MY_LAYER_TEST"
    }
}

###

PUT http://127.0.0.1:8000/collections
Content-Type: application/json

{
    "id": 6,
    "label": "OSM",
    "properties": {
        "Layer": "OSM",
        "nova": "2"
    }
}

###

GET http://127.0.0.1:8000/collections/9/items?page=0&size=10

### ONLY 1

GET http://127.0.0.1:8000/collections/9/items/41

### creare feature

POST http://127.0.0.1:8000/collections/1/item
Content-Type: application/json

{
      "type": "Feature",
      "geometry": {
        "type": "point",
        "coordinates": [
          -38.520302,
          -12.999122
        ]
      },
      "properties": {
        "some": "ABACATE"
      }
}

### creare feature

PUT http://127.0.0.1:8000/collections/2/item
Content-Type: application/json

{
      "id": 39,
      "type": "Feature",
      "geometry": {
        "type": "point",
        "coordinates": [
          -38.520302,
          -12.999122
        ]
      },
      "properties": {
        "some": "ABACATE"
      }
}

### save

POST http://127.0.0.1:8000/execute
Content-Type: application/json

{
    "request": "save_feature",
    "geometry":{"type":"Point","coordinates":[103.0, 0.5]},
    "properties": {"prop1": "8"}
}

### save collection

POST http://127.0.0.1:8000/execute
Content-Type: application/json

{
    "request": "create_collection",
    "label":"my features"
}


